"""
Tests for apt.dat parsing. Uses an inline fixture — no real apt.dat needed.
"""
import tempfile
from pathlib import Path

import pytest
from airport.parser import parse_apt_dat, Airport, Frequency, Runway

# Minimal apt.dat with two airports and one runway each.
# Runway coords for EDDV: thresholds at lon 9.685 and 9.705, lat 52.461 (east-west, ~1.4 km)
_APT_DAT_FIXTURE = """\
I
1100 Generated by test fixture

1 6 0 0 EDDV Hannover Airport
53 12175 Hannover Ground
54 11865 Hannover Tower
50 12625 Hannover Information
100 45.00 1 0 0.25 2 3 0 27 52.461000 9.685000 0.00 0 3 0 0 0 09 52.461000 9.705000 0.00 0 3 0 0 0

1 14 0 0 EDDF Frankfurt Am Main Airport
54 11900 Frankfurt Tower
55 12025 Frankfurt Approach
100 60.00 1 0 0.25 2 3 0 25L 50.026421 8.496921 0.00 0 3 0 0 0 07R 50.037578 8.543367 0.00 0 3 0 0 0

99
"""


@pytest.fixture
def airports(tmp_path):
    apt = tmp_path / "apt.dat"
    apt.write_text(_APT_DAT_FIXTURE)
    cache = tmp_path / "apt.vatc_cache.pkl"
    return parse_apt_dat(apt, cache_path=cache)


class TestParsedAirports:
    def test_both_airports_present(self, airports):
        assert "EDDV" in airports
        assert "EDDF" in airports

    def test_eddv_name(self, airports):
        assert airports["EDDV"].name == "Hannover Airport"

    def test_eddv_elevation(self, airports):
        assert airports["EDDV"].elevation_ft == 6

    def test_eddv_position_is_runway_midpoint(self, airports):
        ap = airports["EDDV"]
        assert abs(ap.lat - 52.461) < 0.001
        assert abs(ap.lon - 9.695) < 0.001   # midpoint of 9.685 and 9.705


class TestFrequencies:
    def test_eddv_has_three_frequencies(self, airports):
        assert len(airports["EDDV"].frequencies) == 3

    def test_ground_frequency(self, airports):
        gnd = airports["EDDV"].ground_freq()
        assert gnd is not None
        assert abs(gnd.freq_mhz - 121.75) < 0.001

    def test_tower_frequency(self, airports):
        twr = airports["EDDV"].tower_freq()
        assert twr is not None
        assert abs(twr.freq_mhz - 118.65) < 0.001

    def test_atis_frequency(self, airports):
        atis = airports["EDDV"].atis_freq()
        assert atis is not None
        assert abs(atis.freq_mhz - 126.25) < 0.001

    def test_no_clearance_returns_none(self, airports):
        assert airports["EDDV"].clearance_freq() is None

    def test_eddf_has_no_ground(self, airports):
        assert airports["EDDF"].ground_freq() is None


class TestRunways:
    def test_eddv_has_one_runway(self, airports):
        assert len(airports["EDDV"].runways) == 1

    def test_runway_names(self, airports):
        rwy = airports["EDDV"].runways[0]
        assert rwy.name1 == "27"
        assert rwy.name2 == "09"

    def test_runway_width(self, airports):
        assert airports["EDDV"].runways[0].width_m == 45.0

    def test_runway_thresholds(self, airports):
        rwy = airports["EDDV"].runways[0]
        assert abs(rwy.lat1 - 52.461) < 0.0001
        assert abs(rwy.lon1 - 9.685) < 0.0001
        assert abs(rwy.lat2 - 52.461) < 0.0001
        assert abs(rwy.lon2 - 9.705) < 0.0001

    def test_runway_summary_format(self, airports):
        s = airports["EDDV"].runway_summary()
        assert "27" in s
        assert "09" in s


class TestSixDigitFrequency:
    def test_six_digit_parsing(self, tmp_path):
        # 6-digit format: 118900 = 118.900 MHz
        content = _APT_DAT_FIXTURE.replace("53 12175 Hannover Ground",
                                           "53 121750 Hannover Ground")
        apt = tmp_path / "apt6.dat"
        apt.write_text(content)
        result = parse_apt_dat(apt, cache_path=tmp_path / "apt6.cache.pkl")
        gnd = result["EDDV"].ground_freq()
        assert abs(gnd.freq_mhz - 121.750) < 0.001


class TestCache:
    def test_cache_is_used_on_second_call(self, tmp_path):
        apt = tmp_path / "apt.dat"
        apt.write_text(_APT_DAT_FIXTURE)
        cache = tmp_path / "cache.pkl"
        first = parse_apt_dat(apt, cache_path=cache)
        assert cache.exists()
        second = parse_apt_dat(apt, cache_path=cache)
        assert set(first.keys()) == set(second.keys())
